### ISSUE TITLE
Misleading associated type KeySize

### ISSUE THREAD

**Issue by Fraser999** [miscreant/miscreant.rs#22]
From [the associated type name and comment](https://github.com/miscreant/miscreant.rs/blob/master/src/aead.rs#L18-L19), I took this to mean it would represent the required size of the `key` passed in [`Aead::new()`](https://github.com/miscreant/miscreant.rs/blob/master/src/aead.rs#L27).  However, it seems to actually represent the underlying cipher's key size and is half of the Aead's key-size.

It also looks like the FFI bindings have fallen into this trap too, both for [encrypt](https://github.com/miscreant/miscreant.rs/blob/master/src/ffi.rs#L214) and [decrypt](https://github.com/miscreant/miscreant.rs/blob/master/src/ffi.rs#L250).  I notice that the FFI test is [compiled but not run](https://github.com/miscreant/miscreant.rs/blob/master/.travis.yml#L30) on Travis.  When I tried to run it, it hung while trying to panic due to the wrong size key being used.  However, after trying to fix that locally, the test crashed with `SIGILL` deriving from the [Mac constructor](https://github.com/miscreant/miscreant.rs/blob/master/src/siv.rs#L78).

A final minor point is that I don't think the comments about which half of the key is used for what tally up with the code in [`Siv::new()`](https://github.com/miscreant/miscreant.rs/blob/master/src/siv.rs#L74-L78).

**Comment by tarcieri** [comment]
The SIGILL is likely that you don't have AES-NI support. Can you provide more information on the machine in question? See also https://github.com/RustCrypto/block-ciphers/issues/25

Regarding the key size, part of the problem is there are two key sizes: the one used by the underlying cipher (i.e. the AES block cipher), and the key used by the SIV construction and its AEAD mode. In this case the associated type refers to the former. I think it would possible to make it be the latter, and then divide by two to get the AES key size, which I think is what you're expecting.

**Comment by Fraser999** [comment]
You're right regarding AES-NI support, the machine I used indeed doesn't have it.  If I run the test with the key sizes doubled in ffi.rs and using the `soft-aes` feature, the test passes.

On the key size; yes, that is what I was expecting.  If it's not simple to implement, possibly just renaming this associated type (to e.g. `AesKeySize`) and documenting it more completely would be enough?  For reference, I think my misunderstanding began after reading [the generated docs](https://docs.rs/miscreant/0.4.2/miscreant/aead/trait.Aead.html#associatedtype.KeySize).

**Comment by Fraser999** [comment]
Accidentally closed this, due to I have fat fingers and not enough coffee yet!

**Comment by tarcieri** [comment]
It should be pretty easy to do with `typenum`:

https://docs.rs/typenum/latest/typenum/macro.op.html
